# Mini Assignment 1

## Group 25

| Name | Matric No. |
| --------- | -------- |
| Goh Haw Yee | 22105316 |
| Heng Wen Yang | 22115428 |
| Yen Hua Shen | 22086174 |
| Daniel Ang Qi En | 24004519 |
| Saiket Das | 22117847 |

## Task 1: Data Importing and Advanced Cleaning

### Data Ingestion
First, import the pandas library. Use the read_csv method to read the patient_records.csv file with the delimiter set as ';'.

In [1]:
import pandas as pd

patient_records = pd.read_csv('patient_records.csv', delimiter=';')
patient_records

,patient_id,admission_date,district,hospital_name,ward,age,blood_oxygen_level,heart_rate
0,ID-#08455-X!,2026-10-29,West,Westview Hospital,Observation,45,99,102.0
1,ID-#05101-K!,2026-10-30,Industrial,Industrial Med,ER,44,92,116.0
2,ID-#01656-L!,2026-10-16,Waterfront,Bayview Hospital,Observation,71,98,72.0
3,ID-#07552-R!,2026-10-26,South,South Park Hospital,ER,88,98,81.0
4,**ID_02536?W,2026-10-16,Industrial,Workers Health Center,General,87,96,118.0
...,...,...,...,...,...,...,...,...
8495,ID-#05714-K!,2026-10-30,Central,Metropolis General,ER,82,100,72.0
8496,ID-#06164-B!,2026-10-30,Industrial,Workers Health Center,General,77,81,95.0
8497,ID-#01057-C!,2026-10-24,Industrial,Industrial Med,ER,61,88,101.0
8498,ID-#02384-L!,2026-10-27,East,Eastern Health,ICU,62,83,104.0
8499,ID-#05865-P!,2026-10-26,West,Westview Hospital,General,38,-,118.0

Read sensor_data.json using the read_json method from pandas

In [2]:
sensor_data = pd.read_json('sensor_data.json')
sensor_data

,sensor_id,district,metric_type,calibration_status,Day1,Day2,Day3,Day4,Day5,Day6,...,Day21,Day22,Day23,Day24,Day25,Day26,Day27,Day28,Day29,Day30
0,SENS-00998,Waterfront,PM2.5,OK,56.48,56.88,51.16,44.35,41.12,48.43,...,56.62,49.85,None,46.36,49.15,56.51,57.63,52.52,45.09,44.71
1,SENS-01118,West,NO2_ppb,UNKNOWN,24.91,26.9,22.18,18.24,None,19.15,...,25.77,21.84,17.73,None,20.63,24.61,26.26,23.0,19.93,19.43
2,SENS-00795,Industrial,NO2_ppb,OK,41.18,36.11,33.54,28.74,25.59,31.67,...,34.94,33.2,30.11,26.62,32.63,38.9,35.39,34.13,29.1,23.67
3,SENS-00208,North,Chemical_X_ppb,OK,27.64,25.28,23.57,16.81,13.0,21.06,...,29.81,22.28,19.36,14.68,21.43,29.86,25.59,None,19.95,16.27
4,SENS-00323,Central,CO2_ppm,OK,42.63,38.58,36.51,28.33,29.51,33.56,...,38.04,35.05,27.2,None,33.92,42.33,43.9,36.19,31.37,28.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,SENS-01599,Waterfront,Chemical_X_ppb,UNKNOWN,50.93,47.62,45.45,37.56,40.7,43.33,...,50.51,44.64,39.14,42.52,43.81,50.61,50.49,46.25,38.91,41.78
9996,SENS-01062,West,PM2.5,OK,44.17,47.09,42.77,36.47,34.84,41.13,...,49.42,42.04,37.13,35.29,40.78,45.66,45.45,43.4,39.7,32.61
9997,SENS-01025,West,NO2_ppb,UNKNOWN,45.71,47.75,40.69,32.81,35.31,37.18,...,42.3,39.36,32.54,33.78,38.18,46.56,42.13,39.99,36.4,34.18
9998,SENS-00263,South,PM2.5,NEEDS_CALIBRATION,56.2,52.09,49.69,45.56,39.66,47.48,...,56.35,48.8,43.74,42.82,48.42,51.38,55.65,51.07,44.3,45.77
9999,SENS-01550,Industrial,CO2_ppm,OK,24.71,25.98,22.16,16.02,18.45,19.16,...,25.62,21.37,13.19,19.08,20.61,27.19,23.52,23.25,15.37,16.92

Read the hospital_capacity.xlsx file by using pd.ExcelFile and identify the sheets in the file. Then, parse each sheet using a for-loop and append each dataframe into a list. Finally, use pd.concat to merge all the dataframes into one singular dataframe.

In [3]:
hospital_excel = pd.ExcelFile('hospital_capacity.xlsx')
hospital_excel.sheet_names

['Central', 'North', 'South', 'East', 'West', 'Industrial', 'Waterfront']

In [4]:
hospital_list = []
for sheet in hospital_excel.sheet_names:
    hospital_list.append(hospital_excel.parse(sheet))

all_hospitals = pd.concat(hospital_list, ignore_index=True)
all_hospitals

,Hospital_Name,Shift,Total_Beds,Available_Beds,Staff_Count
0,Metropolis General,Morning,269.0,84.0,81.0
1,Metropolis General,Evening,325.0,86.0,75.0
2,Metropolis General,Night,383.0,114.0,90.0
3,Central Care,Morning,241.0,108.0,73.0
4,Central Care,Evening,368.0,42.0,100.0
5,Central Care,Night,354.0,85.0,65.0
6,Metropolis General,Audit_Error,NaN,NaN,NaN
7,Northern Medical,Morning,329.0,48.0,97.0
8,Northern Medical,Evening,367.0,114.0,63.0
9,Northern Medical,Night,343.0,82.0,75.0
10,Northside Clinic,Morning,319.0,40.0,67.0
11,Northside Clinic,Evening,281.0,86.0,80.0
12,Northside Clinic,Night,288.0,67.0,60.0
13,South Park Hospital,Morning,442.0,47.0,79.0
14,South Park Hospital,Evening,339.0,58.0,69.0
15,South Park Hospital,Night,238.0,114.0,95.0
16,Eastern Health,Morning,573.0,2.0,55.0
17,Eastern Health,Evening,447.0,7.0,70.0
18,Eastern Health,Night,384.0,3.0,56.0
19,East Point Med,Morning,562.0,4.0,58.0
20,East Point Med,Evening,470.0,1.0,50.0
21,East Point Med,Night,508.0,3.0,50.0
22,Eastern Health,Audit_Error,NaN,NaN,NaN
23,Westview Hospital,Morning,225.0,72.0,73.0
24,Westview Hospital,Evening,208.0,82.0,68.0
25,Westview Hospital,Night,309.0,72.0,76.0
26,Workers Health Center,Morning,379.0,5.0,46.0
27,Workers Health Center,Evening,500.0,1.0,42.0
28,Workers Health Center,Night,432.0,0.0,62.0
29,Industrial Med,Morning,542.0,3.0,46.0
30,Industrial Med,Evening,445.0,8.0,59.0
31,Industrial Med,Night,365.0,5.0,60.0
32,Workers Health Center,Audit_Error,NaN,NaN,NaN
33,Bayview Hospital,Morning,342.0,40.0,66.0
34,Bayview Hospital,Evening,419.0,64.0,68.0
35,Bayview Hospital,Night,382.0,100.0,89.0
36,Bayview Hospital,Audit_Error,NaN,NaN,NaN

### Data Cleaning
For all DataFrames, first coerce any erratic entries such as dashes (-) in numeric columns using *pd.to_numeric()* with the *coerce* argument to force these values to be **NaN**. Then, diagnose the missing data using *.info()* and *.isnull().any()* and clean the data according to the data types. Perform additional data cleaning methods according to the DataFrame itself.

#### patient_records.csv

In [5]:
patient_records['blood_oxygen_level'] = pd.to_numeric(patient_records['blood_oxygen_level'], errors='coerce')
patient_records['age'] = pd.to_numeric(patient_records['age'], errors='coerce')

patient_records.info()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          8500 non-null   str
 1   admission_date      8500 non-null   str
 2   district            8500 non-null   str
 3   hospital_name       8500 non-null   str
 4   ward                8500 non-null   str
 5   age                 8063 non-null   float64
 6   blood_oxygen_level  8169 non-null   float64
 7   heart_rate          8267 non-null   float64
dtypes: float64(3), str(5)
memory usage: 531.4 KB

In [6]:
patient_records[patient_records.isnull().any(axis=1)]

,patient_id,admission_date,district,hospital_name,ward,age,blood_oxygen_level,heart_rate
9,ID-#01744-P!,2026-10-21,Industrial,Workers Health Center,ICU,NaN,84.0,88.0
28,ID-#05285-P!,2026-10-23,Central,Metropolis General,ER,NaN,97.0,77.0
57,ID-#05202-Q!,2026-10-05,North,Northside Clinic,ICU,84.0,NaN,104.0
59,ID-#01438-G!,2026-10-13,West,Westview Hospital,ICU,82.0,93.0,NaN
60,ID-#03465-D!,2026-10-26,North,Northern Medical,General,40.0,98.0,NaN
...,...,...,...,...,...,...,...,...
8470,ID-#02958-D!,2026-10-23,Central,Metropolis General,ER,NaN,97.0,96.0
8474,ID-#04681-T!,2026-10-21,East,Eastern Health,ER,20.0,NaN,106.0
8479,ID-#05238-W!,2026-10-07,Central,Metropolis General,ICU,28.0,NaN,84.0
8483,ID-#04973-P!,2026-10-06,North,Northside Clinic,ER,71.0,93.0,NaN
8499,ID-#05865-P!,2026-10-26,West,Westview Hospital,General,38.0,NaN,118.0

Fill in the missing numerical **heart_rate**, **blood_oxygen_level** and **age** values using the *.median()* method

In [7]:
patient_records['heart_rate'] = patient_records['heart_rate'].fillna(patient_records['heart_rate'].median())
patient_records['blood_oxygen_level'] = patient_records['blood_oxygen_level'].fillna(patient_records['blood_oxygen_level'].median())
patient_records['age'] = patient_records['age'].fillna(patient_records['age'].median())

patient_records.info()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          8500 non-null   str
 1   admission_date      8500 non-null   str
 2   district            8500 non-null   str
 3   hospital_name       8500 non-null   str
 4   ward                8500 non-null   str
 5   age                 8500 non-null   float64
 6   blood_oxygen_level  8500 non-null   float64
 7   heart_rate          8500 non-null   float64
dtypes: float64(3), str(5)
memory usage: 531.4 KB

Replace the **patient_id** values by extracting the numeric part of the ID using *.replace()*. The part to be replaced is represented by a regex, **\D** which means any character that is not a digit is replaced. The value to be replaced is empty. Therefore, the expression strips all characters in the **patient_id** values that is not a number. The regex parameter is set to True to use a regex to find the values that will be replaced.

In [8]:
patient_records['patient_id'] = patient_records['patient_id'].replace(r'\D', '', regex=True)
patient_records

,patient_id,admission_date,district,hospital_name,ward,age,blood_oxygen_level,heart_rate
0,08455,2026-10-29,West,Westview Hospital,Observation,45.0,99.0,102.0
1,05101,2026-10-30,Industrial,Industrial Med,ER,44.0,92.0,116.0
2,01656,2026-10-16,Waterfront,Bayview Hospital,Observation,71.0,98.0,72.0
3,07552,2026-10-26,South,South Park Hospital,ER,88.0,98.0,81.0
4,02536,2026-10-16,Industrial,Workers Health Center,General,87.0,96.0,118.0
...,...,...,...,...,...,...,...,...
8495,05714,2026-10-30,Central,Metropolis General,ER,82.0,100.0,72.0
8496,06164,2026-10-30,Industrial,Workers Health Center,General,77.0,81.0,95.0
8497,01057,2026-10-24,Industrial,Industrial Med,ER,61.0,88.0,101.0
8498,02384,2026-10-27,East,Eastern Health,ICU,62.0,83.0,104.0
8499,05865,2026-10-26,West,Westview Hospital,General,38.0,96.0,118.0

Convert categorical string data **district** and **ward** to the *category* data type and convert **age** to *int64* type.

In [9]:
patient_records['district'] = patient_records['district'].astype('category')
patient_records['ward'] = patient_records['ward'].astype('category')
patient_records['age'] = patient_records['age'].astype('int64')

patient_records.info()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          8500 non-null   str
 1   admission_date      8500 non-null   str
 2   district            8500 non-null   category
 3   hospital_name       8500 non-null   str
 4   ward                8500 non-null   category
 5   age                 8500 non-null   int64
 6   blood_oxygen_level  8500 non-null   float64
 7   heart_rate          8500 non-null   float64
dtypes: category(2), float64(2), int64(1), str(3)
memory usage: 415.3 KB

#### sensor_data.json

In [10]:
sensor_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sensor_id           10000 non-null  str
 1   district            10000 non-null  str
 2   metric_type         10000 non-null  str
 3   calibration_status  10000 non-null  str
 4   Day1                9806 non-null   object
 5   Day2                9794 non-null   object
 6   Day3                9816 non-null   object
 7   Day4                9816 non-null   object
 8   Day5                9806 non-null   object
 9   Day6                9793 non-null   object
 10  Day7                9813 non-null   object
 11  Day8                9802 non-null   object
 12  Day9                9787 non-null   object
 13  Day10               9805 non-null   object
 14  Day11               9810 non-null   object
 15  Day12               9806 non-null   object
 16  Day13               9811 non-null   object
 17  Day14               9795 non-null   object
 18  Day15               9784 non-null   object
 19  Day16               9804 non-null   object
 20  Day17               9786 non-null   object
 21  Day18               9794 non-null   object
 22  Day19               9825 non-null   object
 23  Day20               9789 non-null   object
 24  Day21               9778 non-null   object
 25  Day22               9763 non-null   object
 26  Day23               9796 non-null   object
 27  Day24               9795 non-null   object
 28  Day25               9782 non-null   object
 29  Day26               9794 non-null   object
 30  Day27               9790 non-null   object
 31  Day28               9788 non-null   object
 32  Day29               9783 non-null   object
 33  Day30               9809 non-null   object
dtypes: object(30), str(4)
memory usage: 2.6+ MB

Convert all *object* types into numeric types by first selecting all columns with type *object*. Then, apply the *pd.to_numeric()* function along with the *coerce* argument to convert them to numeric values.

In [11]:
object_cols = sensor_data.select_dtypes(include='object', exclude='str').columns
sensor_data[object_cols] = sensor_data[object_cols].apply(pd.to_numeric, errors='coerce')

sensor_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sensor_id           10000 non-null  str
 1   district            10000 non-null  str
 2   metric_type         10000 non-null  str
 3   calibration_status  10000 non-null  str
 4   Day1                9699 non-null   float64
 5   Day2                9704 non-null   float64
 6   Day3                9706 non-null   float64
 7   Day4                9719 non-null   float64
 8   Day5                9701 non-null   float64
 9   Day6                9694 non-null   float64
 10  Day7                9713 non-null   float64
 11  Day8                9689 non-null   float64
 12  Day9                9693 non-null   float64
 13  Day10               9708 non-null   float64
 14  Day11               9707 non-null   float64
 15  Day12               9705 non-null   float64
 16  Day13               9714 non-null   float64
 17  Day14               9704 non-null   float64
 18  Day15               9694 non-null   float64
 19  Day16               9709 non-null   float64
 20  Day17               9690 non-null   float64
 21  Day18               9697 non-null   float64
 22  Day19               9708 non-null   float64
 23  Day20               9692 non-null   float64
 24  Day21               9674 non-null   float64
 25  Day22               9656 non-null   float64
 26  Day23               9711 non-null   float64
 27  Day24               9701 non-null   float64
 28  Day25               9679 non-null   float64
 29  Day26               9685 non-null   float64
 30  Day27               9704 non-null   float64
 31  Day28               9675 non-null   float64
 32  Day29               9694 non-null   float64
 33  Day30               9707 non-null   float64
dtypes: float64(30), str(4)
memory usage: 2.6 MB

Fill in the missing numerical values using *.median()* method. First select all the numerical columns, then use the method to fill in the missing values.

In [12]:
numeric_cols = sensor_data.select_dtypes(include='float64').columns

sensor_data[numeric_cols] = sensor_data[numeric_cols].fillna(sensor_data[numeric_cols].median())
sensor_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sensor_id           10000 non-null  str
 1   district            10000 non-null  str
 2   metric_type         10000 non-null  str
 3   calibration_status  10000 non-null  str
 4   Day1                10000 non-null  float64
 5   Day2                10000 non-null  float64
 6   Day3                10000 non-null  float64
 7   Day4                10000 non-null  float64
 8   Day5                10000 non-null  float64
 9   Day6                10000 non-null  float64
 10  Day7                10000 non-null  float64
 11  Day8                10000 non-null  float64
 12  Day9                10000 non-null  float64
 13  Day10               10000 non-null  float64
 14  Day11               10000 non-null  float64
 15  Day12               10000 non-null  float64
 16  Day13               10000 non-null  float64
 17  Day14               10000 non-null  float64
 18  Day15               10000 non-null  float64
 19  Day16               10000 non-null  float64
 20  Day17               10000 non-null  float64
 21  Day18               10000 non-null  float64
 22  Day19               10000 non-null  float64
 23  Day20               10000 non-null  float64
 24  Day21               10000 non-null  float64
 25  Day22               10000 non-null  float64
 26  Day23               10000 non-null  float64
 27  Day24               10000 non-null  float64
 28  Day25               10000 non-null  float64
 29  Day26               10000 non-null  float64
 30  Day27               10000 non-null  float64
 31  Day28               10000 non-null  float64
 32  Day29               10000 non-null  float64
 33  Day30               10000 non-null  float64
dtypes: float64(30), str(4)
memory usage: 2.6 MB

Convert the **district**, **metric_type** and **calibration_status** columns to *category* data types.

In [13]:
sensor_data['district'] = sensor_data['district'].astype('category')
sensor_data['metric_type'] = sensor_data['metric_type'].astype('category')
sensor_data['calibration_status'] = sensor_data['calibration_status'].astype('category')

sensor_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sensor_id           10000 non-null  str
 1   district            10000 non-null  category
 2   metric_type         10000 non-null  category
 3   calibration_status  10000 non-null  category
 4   Day1                10000 non-null  float64
 5   Day2                10000 non-null  float64
 6   Day3                10000 non-null  float64
 7   Day4                10000 non-null  float64
 8   Day5                10000 non-null  float64
 9   Day6                10000 non-null  float64
 10  Day7                10000 non-null  float64
 11  Day8                10000 non-null  float64
 12  Day9                10000 non-null  float64
 13  Day10               10000 non-null  float64
 14  Day11               10000 non-null  float64
 15  Day12               10000 non-null  float64
 16  Day13               10000 non-null  float64
 17  Day14               10000 non-null  float64
 18  Day15               10000 non-null  float64
 19  Day16               10000 non-null  float64
 20  Day17               10000 non-null  float64
 21  Day18               10000 non-null  float64
 22  Day19               10000 non-null  float64
 23  Day20               10000 non-null  float64
 24  Day21               10000 non-null  float64
 25  Day22               10000 non-null  float64
 26  Day23               10000 non-null  float64
 27  Day24               10000 non-null  float64
 28  Day25               10000 non-null  float64
 29  Day26               10000 non-null  float64
 30  Day27               10000 non-null  float64
 31  Day28               10000 non-null  float64
 32  Day29               10000 non-null  float64
 33  Day30               10000 non-null  float64
dtypes: category(3), float64(30), str(1)
memory usage: 2.4 MB

#### hospital_capacity.xlsx

In [14]:
all_hospitals.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hospital_Name   37 non-null     str
 1   Shift           37 non-null     str
 2   Total_Beds      33 non-null     float64
 3   Available_Beds  33 non-null     float64
 4   Staff_Count     33 non-null     float64
dtypes: float64(3), str(2)
memory usage: 1.6 KB

In [15]:
all_hospitals[all_hospitals.isnull().any(axis=1)]

,Hospital_Name,Shift,Total_Beds,Available_Beds,Staff_Count
6,Metropolis General,Audit_Error,NaN,NaN,NaN
22,Eastern Health,Audit_Error,NaN,NaN,NaN
32,Workers Health Center,Audit_Error,NaN,NaN,NaN
36,Bayview Hospital,Audit_Error,NaN,NaN,NaN

Drop all rows with missing data as they are Audit Errors

In [16]:
all_hospitals = all_hospitals.dropna()
all_hospitals.info()

<class 'pandas.DataFrame'>
Index: 33 entries, 0 to 35
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hospital_Name   33 non-null     str
 1   Shift           33 non-null     str
 2   Total_Beds      33 non-null     float64
 3   Available_Beds  33 non-null     float64
 4   Staff_Count     33 non-null     float64
dtypes: float64(3), str(2)
memory usage: 1.5 KB

Convert **Shift** column to a *category* data type.

In [17]:
all_hospitals['Shift'] = all_hospitals['Shift'].astype('category')

all_hospitals.info()

<class 'pandas.DataFrame'>
Index: 33 entries, 0 to 35
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hospital_Name   33 non-null     str
 1   Shift           33 non-null     category
 2   Total_Beds      33 non-null     float64
 3   Available_Beds  33 non-null     float64
 4   Staff_Count     33 non-null     float64
dtypes: category(1), float64(3), str(1)
memory usage: 1.3 KB